/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Ethereal Professional — Lucid Gallery palette
        "on-tertiary-fixed-variant": "#514972",
        "tertiary-fixed": "#d3c8f9",
        "on-tertiary-container": "#484068",
        "secondary-fixed": "#d7e3f8",
        "on-surface": "#2d333b",
        "on-background": "#2d333b",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#515c6d",
        "surface-variant": "#dde3ee",
        "surface-container-high": "#e4e8f2",
        "inverse-on-surface": "#9b9da2",
        "secondary": "#546071",
        "on-surface-variant": "#595f69",
        "tertiary-dim": "#564d77",
        "on-secondary-fixed": "#344050",
        "primary-fixed-dim": "#6e98e7",
        "inverse-primary": "#7ca5f6",
        "on-error-container": "#6e0a12",
        "tertiary": "#625983",
        "outline-variant": "#acb2bd",
        "outline": "#757b85",
        "on-primary-container": "#002657",
        "surface-dim": "#d5dae5",
        "surface-tint": "#305ea9",
        "primary-fixed": "#7ca5f6",
        "error": "#a83836",
        "on-primary-fixed": "#000617",
        "secondary-fixed-dim": "#c9d5e9",
        "surface-container-highest": "#dde3ee",
        "background": "#f8f9ff",
        "on-error": "#fff7f6",
        "error-container": "#fa746f",
        "error-dim": "#67040d",
        "on-primary": "#f9f8ff",
        "inverse-surface": "#0b0e12",
        "primary": "#305ea9",
        "tertiary-container": "#d3c8f9",
        "on-secondary-container": "#475363",
        "surface-container": "#eaeef7",
        "primary-container": "#7ca5f6",
        "on-primary-fixed-variant": "#002f68",
        "surface-container-low": "#f1f3fb",
        "primary-dim": "#20519c",
        "secondary-dim": "#485465",
        "surface": "#f8f9ff",
        "on-secondary": "#f7f9ff",
        "surface-bright": "#f8f9ff",
        "tertiary-fixed-dim": "#c5baeb",
        "secondary-container": "#d7e3f8",
        "on-tertiary-fixed": "#342c54",
        "on-tertiary": "#fdf7ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      boxShadow: {
        glass: "0 10px 40px rgba(45,51,59,0.04)",
        "glass-lg": "0 20px 60px rgba(45,51,59,0.08)",
        "tinted": "0 10px 40px rgba(48,94,169,0.12)",
        "ambient": "0 10px 40px rgba(45,51,59,0.04)",
      },
      backdropBlur: {
        "2xl": "32px",
        "3xl": "48px",
      },
      animation: {
        "pulse-dot": "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-slide-up": "fadeSlideUp 0.5s ease forwards",
      },
      keyframes: {
        fadeSlideUp: {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
}
