"""
PulseIQ — Step 1: Daily Feature Aggregation (V4.0: ML Upgrade)
===============================================================
Reads raw CSVs and produces daily_features.csv with one row per
(employee, day).

Changes from V3.2:
  - RoBERTa sentiment: replaces the synthetic sentiment_score float
    with real inference from cardiffnlp/twitter-roberta-base-sentiment.
    Graceful fallback to the existing numeric column if transformers/torch
    not installed (so the pipeline never breaks).
  - New NLP features per (employee, day):
      slack_sentiment_volatility  — std of per-message sentiments (mood instability)
      slack_avg_stress_score      — keyword-based burnout language frequency
  - Git aggregation: reads git_commits.csv (generated by generate_data.py)
      git_commits_total, git_lines_added, git_lines_deleted, git_lines_changed,
      git_distinct_repos, git_commits_after_hours, git_commits_weekend
  - Zoom aggregation: reads zoom_meetings.csv
      zoom_meetings_count, zoom_total_minutes, zoom_speaking_seconds,
      zoom_speaking_ratio (speaking / (duration * 60)), zoom_avg_participants

Output format is a strict superset of V3.2 — all existing columns kept,
new columns appended. compute_baselines.py and compute_burnout.py consume
these automatically.

Run AFTER generate_data.py.
"""

import csv
import statistics as _stats
from collections import defaultdict
from datetime import datetime, timedelta
from pathlib import Path

DATA_DIR   = Path("pulseiq_data")
OUTPUT_FILE = DATA_DIR / "daily_features.csv"

AFTER_HOURS_START = 21   # 9 pm
AFTER_HOURS_END   = 7    # 7 am
SOCIAL_CHANNELS   = {"#random", "#general"}

# ---------------------------------------------------------------------------
# RoBERTa sentiment — lazy-loaded; pipeline never breaks without it
# ---------------------------------------------------------------------------
_nlp_pipeline  = None
_nlp_available = False

def _load_nlp():
    global _nlp_pipeline, _nlp_available
    try:
        from transformers import pipeline as hf_pipeline
        print("  Loading RoBERTa sentiment model "
              "(cardiffnlp/twitter-roberta-base-sentiment)...")
        _nlp_pipeline = hf_pipeline(
            "sentiment-analysis",
            model="cardiffnlp/twitter-roberta-base-sentiment",
            tokenizer="cardiffnlp/twitter-roberta-base-sentiment",
            truncation=True,
            max_length=512,
        )
        _nlp_available = True
        print("  RoBERTa loaded ✓")
    except ImportError:
        print("  [WARN] transformers/torch not installed — "
              "using fallback numeric sentiment from CSV.")
        _nlp_available = False

# cardiffnlp label map  LABEL_0=negative  LABEL_1=neutral  LABEL_2=positive
_LABEL_TO_SCORE = {"LABEL_0": 0.1, "LABEL_1": 0.5, "LABEL_2": 0.9}

def _score_text(text: str, fallback: float) -> float:
    """Return 0–1 sentiment. Uses RoBERTa when available, else fallback."""
    if not _nlp_available or not text.strip():
        return fallback
    result = _nlp_pipeline(text[:512])[0]
    base   = _LABEL_TO_SCORE.get(result["label"], 0.5)
    # Weight by model confidence so borderline predictions stay near 0.5
    return round(0.5 + (base - 0.5) * result["score"], 3)

# Lightweight burnout-language keyword set (supplements RoBERTa)
_STRESS_KEYWORDS = {
    "deadline", "stuck", "broken", "blocked", "overtime", "exhausted",
    "behind", "overloaded", "cant", "urgent", "escalation", "terrible",
    "nightmare", "swamped", "drowning", "overwhelmed", "burned", "hate",
}

def _stress_score(text: str) -> float:
    """0–1: fraction of stress-keyword hits, capped at 1."""
    words = set(text.lower().split())
    return min(1.0, len(words & _STRESS_KEYWORDS) / 3.0)

# ---------------------------------------------------------------------------
# Loaders
# ---------------------------------------------------------------------------
def load_employees():
    with open(DATA_DIR / "employees.csv") as f:
        return {r["employee_id"]: r for r in csv.DictReader(f)}

def load_slack():
    rows = []
    with open(DATA_DIR / "slack_messages.csv") as f:
        for r in csv.DictReader(f):
            r["timestamp"]       = datetime.strptime(r["timestamp"], "%Y-%m-%d %H:%M:%S")
            r["message_length"]  = int(r["message_length"])
            r["sentiment_score"] = float(r["sentiment_score"])
            r["is_dm"]           = r["is_dm"] == "true"
            rows.append(r)
    return rows

def load_jira():
    rows = []
    with open(DATA_DIR / "jira_events.csv") as f:
        for r in csv.DictReader(f):
            r["timestamp"]    = datetime.strptime(r["timestamp"], "%Y-%m-%d %H:%M:%S")
            r["story_points"] = int(r["story_points"])
            rows.append(r)
    return rows

def load_calendar():
    rows = []
    with open(DATA_DIR / "calendar_events.csv") as f:
        for r in csv.DictReader(f):
            r["date"]           = datetime.strptime(r["date"], "%Y-%m-%d").date()
            r["start_min"]      = (int(r["start_time"].split(":")[0]) * 60
                                   + int(r["start_time"].split(":")[1]))
            r["end_min"]        = (int(r["end_time"].split(":")[0]) * 60
                                   + int(r["end_time"].split(":")[1]))
            r["attendee_count"] = int(r["attendee_count"])
            rows.append(r)
    return rows

def load_git():
    path = DATA_DIR / "git_commits.csv"
    if not path.exists():
        return []
    rows = []
    with open(path) as f:
        for r in csv.DictReader(f):
            r["timestamp"]     = datetime.strptime(r["timestamp"], "%Y-%m-%d %H:%M:%S")
            r["lines_added"]   = int(r["lines_added"])
            r["lines_deleted"] = int(r["lines_deleted"])
            rows.append(r)
    return rows

def load_zoom():
    path = DATA_DIR / "zoom_meetings.csv"
    if not path.exists():
        return []
    rows = []
    with open(path) as f:
        for r in csv.DictReader(f):
            r["date"]              = datetime.strptime(r["date"], "%Y-%m-%d").date()
            r["duration_minutes"]  = int(r["duration_minutes"])
            r["speaking_seconds"]  = int(r["speaking_seconds"])
            r["participant_count"] = int(r["participant_count"])
            rows.append(r)
    return rows

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _is_after_hours(dt: datetime) -> bool:
    return dt.hour >= AFTER_HOURS_START or dt.hour < AFTER_HOURS_END

def _is_weekend(d) -> bool:
    if isinstance(d, datetime):
        d = d.date()
    return d.weekday() >= 5

# ---------------------------------------------------------------------------
# Feature computation — Slack
# ---------------------------------------------------------------------------
def compute_slack_features(slack_rows):
    """
    Per (employee, date) slack features.
    New vs V3.2: slack_sentiment_volatility, slack_avg_stress_score.
    Sentiment is now RoBERTa-scored (or fallback) per message.
    """
    acc = defaultdict(lambda: {
        "total": 0, "after_hours": 0, "weekend": 0,
        "work_ch": 0, "social_ch": 0, "dms": 0,
        "channels": set(), "dm_partners": set(),
        "sentiments": [], "stresses": [],
    })

    for r in slack_rows:
        key = (r["employee_id"], r["timestamp"].date())
        a   = acc[key]
        a["total"] += 1

        if _is_after_hours(r["timestamp"]):
            a["after_hours"] += 1
        if _is_weekend(r["timestamp"]):
            a["weekend"] += 1

        if r["is_dm"]:
            a["dms"] += 1
            if r["recipient_id"]:
                a["dm_partners"].add(r["recipient_id"])
        else:
            a["channels"].add(r["channel"])
            if r["channel"] in SOCIAL_CHANNELS:
                a["social_ch"] += 1
            else:
                a["work_ch"] += 1

        text      = r.get("message_text", "")
        fallback  = r["sentiment_score"]
        sent      = _score_text(text, fallback)
        stress    = _stress_score(text)
        a["sentiments"].append(sent)
        a["stresses"].append(stress)

    out = {}
    for key, a in acc.items():
        n          = len(a["sentiments"])
        avg_sent   = round(sum(a["sentiments"]) / n, 3) if n else 0.0
        avg_stress = round(sum(a["stresses"]) / n, 3)   if n else 0.0
        volatility = round(_stats.stdev(a["sentiments"]), 3) if n >= 2 else 0.0

        out[key] = {
            "slack_msgs_total":              a["total"],
            "slack_msgs_after_hours":        a["after_hours"],
            "slack_msgs_weekend":            a["weekend"],
            "slack_msgs_work_channels":      a["work_ch"],
            "slack_msgs_social_channels":    a["social_ch"],
            "slack_dms_sent":                a["dms"],
            "slack_distinct_channels":       len(a["channels"]),
            "slack_distinct_dm_partners":    len(a["dm_partners"]),
            "slack_avg_sentiment":           avg_sent,
            "slack_sentiment_volatility":    volatility,
            "slack_avg_stress_score":        avg_stress,
        }
    return out

# ---------------------------------------------------------------------------
# Feature computation — Jira (unchanged)
# ---------------------------------------------------------------------------
def compute_jira_features(jira_rows):
    acc = defaultdict(lambda: {
        "events": 0, "tickets": set(), "closed": 0, "sp_closed": 0, "comments": 0,
    })
    for r in jira_rows:
        key = (r["employee_id"], r["timestamp"].date())
        a   = acc[key]
        a["events"] += 1
        a["tickets"].add(r["ticket_id"])
        if r["event_type"] == "comment":
            a["comments"] += 1
        if r["to_status"] == "Done":
            a["closed"] += 1
            a["sp_closed"] += r["story_points"]

    return {
        key: {
            "jira_events":              a["events"],
            "jira_distinct_tickets":    len(a["tickets"]),
            "jira_tickets_closed":      a["closed"],
            "jira_story_points_closed": a["sp_closed"],
            "jira_comments":            a["comments"],
        }
        for key, a in acc.items()
    }

# ---------------------------------------------------------------------------
# Feature computation — Calendar (unchanged)
# ---------------------------------------------------------------------------
def compute_calendar_features(cal_rows):
    by_key = defaultdict(list)
    for r in cal_rows:
        by_key[(r["employee_id"], r["date"])].append(r)

    WORK_START, WORK_END = 9 * 60, 18 * 60
    out = {}
    for key, meetings in by_key.items():
        meetings.sort(key=lambda m: m["start_min"])
        total_min = sum(m["end_min"] - m["start_min"] for m in meetings)
        attendees = sum(m["attendee_count"]             for m in meetings)

        b2b = sum(
            1 for i in range(1, len(meetings))
            if 0 <= meetings[i]["start_min"] - meetings[i-1]["end_min"] < 15
        )

        intervals = sorted(
            (max(m["start_min"], WORK_START), min(m["end_min"], WORK_END))
            for m in meetings
            if max(m["start_min"], WORK_START) < min(m["end_min"], WORK_END)
        )
        cursor, largest_gap = WORK_START, 0
        for s, e in intervals:
            if s > cursor:
                largest_gap = max(largest_gap, s - cursor)
            cursor = max(cursor, e)
        if cursor < WORK_END:
            largest_gap = max(largest_gap, WORK_END - cursor)
        if not meetings:
            largest_gap = WORK_END - WORK_START

        out[key] = {
            "meetings_count":            len(meetings),
            "meetings_total_minutes":    total_min,
            "meetings_attendees_total":  attendees,
            "meetings_back_to_back":     b2b,
            "largest_focus_gap_minutes": largest_gap,
        }
    return out

# ---------------------------------------------------------------------------
# Feature computation — Git (NEW)
# ---------------------------------------------------------------------------
def compute_git_features(git_rows):
    """
    Per (employee, date):
      git_commits_total       — number of commits
      git_lines_added         — total lines added
      git_lines_deleted       — total lines deleted
      git_lines_changed       — added + deleted (proxy for code churn)
      git_distinct_repos      — distinct repos touched
      git_commits_after_hours — commits outside 7am–9pm
      git_commits_weekend     — commits on Sat/Sun
    """
    acc = defaultdict(lambda: {
        "total": 0, "added": 0, "deleted": 0, "repos": set(),
        "after_hours": 0, "weekend": 0,
    })
    for r in git_rows:
        key = (r["employee_id"], r["timestamp"].date())
        a   = acc[key]
        a["total"]   += 1
        a["added"]   += r["lines_added"]
        a["deleted"] += r["lines_deleted"]
        a["repos"].add(r["repo"])
        if _is_after_hours(r["timestamp"]):
            a["after_hours"] += 1
        if _is_weekend(r["timestamp"]):
            a["weekend"] += 1

    return {
        key: {
            "git_commits_total":       a["total"],
            "git_lines_added":         a["added"],
            "git_lines_deleted":       a["deleted"],
            "git_lines_changed":       a["added"] + a["deleted"],
            "git_distinct_repos":      len(a["repos"]),
            "git_commits_after_hours": a["after_hours"],
            "git_commits_weekend":     a["weekend"],
        }
        for key, a in acc.items()
    }

# ---------------------------------------------------------------------------
# Feature computation — Zoom (NEW)
# ---------------------------------------------------------------------------
def compute_zoom_features(zoom_rows):
    """
    Per (employee, date):
      zoom_meetings_count     — number of Zoom sessions
      zoom_total_minutes      — sum of durations
      zoom_speaking_seconds   — total self-speaking time
      zoom_speaking_ratio     — speaking_seconds / (total_meeting_seconds)
                                capped at 1.0; proxy for participation/withdrawal
      zoom_avg_participants   — mean participant count (proxy for meeting size)
    """
    acc = defaultdict(lambda: {
        "count": 0, "minutes": 0, "speaking": 0,
        "participants": [], "total_seconds": 0,
    })
    for r in zoom_rows:
        key = (r["employee_id"], r["date"])
        a   = acc[key]
        a["count"]        += 1
        a["minutes"]      += r["duration_minutes"]
        a["speaking"]     += r["speaking_seconds"]
        a["total_seconds"]+= r["duration_minutes"] * 60
        a["participants"].append(r["participant_count"])

    out = {}
    for key, a in acc.items():
        ratio = (
            round(a["speaking"] / a["total_seconds"], 3)
            if a["total_seconds"] > 0 else 0.0
        )
        avg_p = (
            round(sum(a["participants"]) / len(a["participants"]), 1)
            if a["participants"] else 0.0
        )
        out[key] = {
            "zoom_meetings_count":   a["count"],
            "zoom_total_minutes":    a["minutes"],
            "zoom_speaking_seconds": a["speaking"],
            "zoom_speaking_ratio":   min(1.0, ratio),
            "zoom_avg_participants": avg_p,
        }
    return out

# ---------------------------------------------------------------------------
# Main aggregation
# ---------------------------------------------------------------------------
def main():
    _load_nlp()

    print("Loading raw CSVs...")
    employees = load_employees()
    slack     = load_slack()
    jira      = load_jira()
    calendar  = load_calendar()
    git       = load_git()
    zoom      = load_zoom()
    print(f"  {len(employees)} employees | {len(slack):,} slack | "
          f"{len(jira):,} jira | {len(calendar):,} cal | "
          f"{len(git):,} git | {len(zoom):,} zoom")

    print("Computing per-day features...")
    slack_f = compute_slack_features(slack)
    jira_f  = compute_jira_features(jira)
    cal_f   = compute_calendar_features(calendar)
    git_f   = compute_git_features(git)
    zoom_f  = compute_zoom_features(zoom)

    all_dates  = sorted({r["timestamp"].date() for r in slack})
    start_date = all_dates[0]
    end_date   = all_dates[-1]
    num_days   = (end_date - start_date).days + 1
    print(f"  Date range: {start_date} → {end_date} ({num_days} days)")
    print(f"  NLP mode: {'RoBERTa' if _nlp_available else 'fallback (numeric)'}")

    # Column order — existing columns first (backward compat), then new ones
    feature_columns = [
        # identifiers
        "employee_id", "name", "team", "persona",
        "date", "day_index", "weekday", "is_weekend",
        # slack (original)
        "slack_msgs_total", "slack_msgs_after_hours", "slack_msgs_weekend",
        "slack_msgs_work_channels", "slack_msgs_social_channels",
        "slack_dms_sent", "slack_distinct_channels", "slack_distinct_dm_partners",
        "slack_avg_sentiment",
        # slack (new NLP features)
        "slack_sentiment_volatility",
        "slack_avg_stress_score",
        # jira (original)
        "jira_events", "jira_distinct_tickets", "jira_tickets_closed",
        "jira_story_points_closed", "jira_comments",
        # calendar (original)
        "meetings_count", "meetings_total_minutes", "meetings_attendees_total",
        "meetings_back_to_back", "largest_focus_gap_minutes",
        # derived ratios (original)
        "after_hours_ratio", "social_msg_ratio",
        # git (new)
        "git_commits_total", "git_lines_added", "git_lines_deleted",
        "git_lines_changed", "git_distinct_repos",
        "git_commits_after_hours", "git_commits_weekend",
        # zoom (new)
        "zoom_meetings_count", "zoom_total_minutes",
        "zoom_speaking_seconds", "zoom_speaking_ratio", "zoom_avg_participants",
    ]

    rows_written = 0
    with open(OUTPUT_FILE, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(feature_columns)

        for eid, emp in employees.items():
            for i in range(num_days):
                d   = start_date + timedelta(days=i)
                key = (eid, d)

                sf = slack_f.get(key, {})
                jf = jira_f.get(key, {})
                cf = cal_f.get(key, {})
                gf = git_f.get(key, {})
                zf = zoom_f.get(key, {})

                msgs_total  = sf.get("slack_msgs_total", 0)
                msgs_after  = sf.get("slack_msgs_after_hours", 0)
                msgs_social = sf.get("slack_msgs_social_channels", 0)

                after_hours_ratio = round(msgs_after  / msgs_total, 3) if msgs_total else 0.0
                social_msg_ratio  = round(msgs_social / msgs_total, 3) if msgs_total else 0.0

                largest_gap = cf.get(
                    "largest_focus_gap_minutes",
                    9 * 60 if not _is_weekend(d) else 0
                )

                w.writerow([
                    # identifiers
                    eid, emp["name"], emp["team"], emp["persona"],
                    d.isoformat(), i, d.weekday(), 1 if _is_weekend(d) else 0,
                    # slack original
                    msgs_total, msgs_after, sf.get("slack_msgs_weekend", 0),
                    sf.get("slack_msgs_work_channels", 0), msgs_social,
                    sf.get("slack_dms_sent", 0),
                    sf.get("slack_distinct_channels", 0),
                    sf.get("slack_distinct_dm_partners", 0),
                    sf.get("slack_avg_sentiment", 0.0),
                    # slack NLP
                    sf.get("slack_sentiment_volatility", 0.0),
                    sf.get("slack_avg_stress_score", 0.0),
                    # jira
                    jf.get("jira_events", 0),
                    jf.get("jira_distinct_tickets", 0),
                    jf.get("jira_tickets_closed", 0),
                    jf.get("jira_story_points_closed", 0),
                    jf.get("jira_comments", 0),
                    # calendar
                    cf.get("meetings_count", 0),
                    cf.get("meetings_total_minutes", 0),
                    cf.get("meetings_attendees_total", 0),
                    cf.get("meetings_back_to_back", 0),
                    largest_gap,
                    # derived
                    after_hours_ratio, social_msg_ratio,
                    # git
                    gf.get("git_commits_total", 0),
                    gf.get("git_lines_added", 0),
                    gf.get("git_lines_deleted", 0),
                    gf.get("git_lines_changed", 0),
                    gf.get("git_distinct_repos", 0),
                    gf.get("git_commits_after_hours", 0),
                    gf.get("git_commits_weekend", 0),
                    # zoom
                    zf.get("zoom_meetings_count", 0),
                    zf.get("zoom_total_minutes", 0),
                    zf.get("zoom_speaking_seconds", 0),
                    zf.get("zoom_speaking_ratio", 0.0),
                    zf.get("zoom_avg_participants", 0.0),
                ])
                rows_written += 1

    print(f"\nWrote {rows_written:,} rows → {OUTPUT_FILE}")
    print(f"  Total feature columns: {len(feature_columns)}")

if __name__ == "__main__":
    main()